// <auto-generated />
using GestaoEscolar.Web.Api.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoEscolar.Web.Api.Repository.Migrations
{
    [DbContext(typeof(GestaoEscolarContext))]
    partial class GestaoEscolarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdTurma")
                        .HasColumnType("bigint")
                        .HasColumnName("idturma");

                    b.Property<string>("Matricula")
                        .HasColumnType("text")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdTurma");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.AlunoDisciplina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdAluno")
                        .HasColumnType("bigint")
                        .HasColumnName("idaluno");

                    b.Property<long>("IdDisciplina")
                        .HasColumnType("bigint")
                        .HasColumnName("iddisciplina");

                    b.Property<double>("Nota1")
                        .HasColumnType("double precision")
                        .HasColumnName("nota1");

                    b.Property<double>("Nota2")
                        .HasColumnType("double precision")
                        .HasColumnName("nota2");

                    b.Property<double>("Nota3")
                        .HasColumnType("double precision")
                        .HasColumnName("nota3");

                    b.Property<double>("Nota4")
                        .HasColumnType("double precision")
                        .HasColumnName("nota4");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdDisciplina");

                    b.ToTable("alunodisciplina", (string)null);
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Disciplina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("disciplina", (string)null);
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Turma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Periodo")
                        .HasColumnType("text")
                        .HasColumnName("periodo");

                    b.HasKey("Id");

                    b.ToTable("turma", (string)null);
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Aluno", b =>
                {
                    b.HasOne("GestaoEscolar.Web.Api.Model.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.AlunoDisciplina", b =>
                {
                    b.HasOne("GestaoEscolar.Web.Api.Model.Aluno", "Aluno")
                        .WithMany("AlunoDisciplinas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("GestaoEscolar.Web.Api.Model.Disciplina", "Disciplina")
                        .WithMany("AlunoDisciplinas")
                        .HasForeignKey("IdDisciplina")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Aluno", b =>
                {
                    b.Navigation("AlunoDisciplinas");
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Disciplina", b =>
                {
                    b.Navigation("AlunoDisciplinas");
                });

            modelBuilder.Entity("GestaoEscolar.Web.Api.Model.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
